ControleFinancas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path('accounts/', include("django.contrib.auth.urls")), #!Adicionar django.contrib.auth.urls para login/logout
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),

]


handler404 = 'core.views.page_404_view'

core/urls.py
from django.urls import path
from core.views import *

app_name = "core"
urlpatterns = [
    path("", TrasactionListView.as_view(), name="list_transaction"),
    path("create/", TransactionCreateView.as_view(), name="create_transaction"),
    path("update/<int:pk>/", TransactionUpdateView.as_view(), name="update_transaction"),
    path("delete/<int:pk>/", TransactionDeleteView.as_view(), name="delete_transaction"),
    path("create-category/", CategoryCreateView.as_view() , name="create_category"),
    path("list-category/", CategoryListView.as_view() , name="list_category"),
    path("delete-category/<int:pk>/", CategoryDeleteView.as_view() , name="delete_category"),
    path("ajax/new-category/", create_category_modal, name="new_category"),

]   

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Client(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField(verbose_name="Idade")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name.upper()


class Category(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=50, verbose_name="Nome")
    is_active = models.BooleanField(verbose_name="Ativo?", default = True, null=True, blank=True)

    def __str__(self):
        return self.name.upper()
    
class Transaction(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50, verbose_name="Título") 
    value = models.DecimalField(max_digits=7, decimal_places=2, verbose_name = "Valor")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Categoria", blank=True, null=True)
    date_now = models.DateTimeField(auto_now=True)
    date_trasaction = models.DateField(verbose_name="Data da Transação")
    description = models.TextField(verbose_name="Descrição", blank=True)
    

    def __str__(self):
        return self.title.upper()

    class Meta:
        ordering = ["-date_now"]






    

    
    

core/forms.py
from django.forms import ModelForm, Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from core.models import *





class TransactionForm(ModelForm):

    class Meta:
        model = Transaction
        fields = "__all__"
        exclude = ["client", ]

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
        exclude = ["client", "is_active", ]



   

core/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from core.models import *
from core.forms import *

from django.http import HttpResponseRedirect
from django.http.response import JsonResponse


#! Transaction
class TrasactionListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "core/modules/transaction/list_transaction.html"
    context_object_name = "transactions"
    paginate_by = 8

    
    def get_context_data(self, **kwargs):
        context = super(TrasactionListView, self).get_context_data(**kwargs)
        context['search_not_exist'] = True if (context['transactions'].count() == 0 and self.request.GET) else False
        context.update()
        return context
    
    def get_queryset(self, *args, **kwargs):
        qs = super(TrasactionListView, self).get_queryset(*args, **kwargs) 
        search = self.request.GET.get("id_search", None)
        
        

        if self.request.user.is_superuser is False:
            qs = qs.filter(client__user = self.request.user)
        
        if search is not None:
            qs = qs.filter(title__icontains = search)

        return qs 

  

class TransactionCreateView(LoginRequiredMixin, CreateView):
    model = Transaction
    form_class = TransactionForm
    template_name = "core/modules/transaction/create_transaction.html"
    success_url = reverse_lazy('core:list_transaction')

    def get_category_by_user(self, user):
        category = Category.objects.all()

        if (user.is_superuser is False):
            category = Category.objects.filter(client__user = user, is_active = True)
        
        return category

    def get_context_data(self, **kwargs):
        context = super(TransactionCreateView, self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = self.get_category_by_user(self.request.user)
        return context

    def form_valid(self, form):
        self.object = form.save()
        temp_client = Client.objects.get(user = self.request.user)
        self.object.client = temp_client
        self.object.save()

        return super().form_valid(form)

class TransactionUpdateView(LoginRequiredMixin, UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name = "core/modules/transaction/update_transaction.html"
    success_url = reverse_lazy('core:list_transaction')

    def get_category_by_user(self, user):
        category = Category.objects.all()

        if (user.is_superuser is False):
            category = Category.objects.filter(client__user = user, is_active = True)
        
        return category

    def get_context_data(self, **kwargs):
        context = super(TransactionUpdateView, self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = self.get_category_by_user(self.request.user)
        return context

class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    success_url = reverse_lazy('core:list_transaction')

#! Category
class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = "core/modules/category/list_category.html"
    context_object_name = "categories"
    paginate_by = 3

    def get_queryset(self, *args, **kwargs):
        qs  = super(CategoryListView, self).get_queryset(*args, **kwargs)
        if self.request.user.is_superuser is False:
            qs = qs.filter(client__user = self.request.user)
        return qs

class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    
    def get_success_url(self):
        return self.request.META.get("HTTP_REFERER")




class CategoryCreateView(LoginRequiredMixin, View):
    model = Category
    form_class = CategoryForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            temp_client = Client.objects.get(user = self.request.user)
            self.object.client = temp_client
            self.object.save()
            
            data = {
                "status": 200,
                "id": self.object.pk,
                "name": self.object.name.upper(),
            }

        else:

            data = {
                "status": 500,
                "id": None,
                "name": None,
            }
        return data
        

        
        

    def post(self, request, *args, **kwargs):
        form = CategoryForm(request.POST)
        data = self.form_valid(form)
        return JsonResponse(data)


def create_category_modal(request):
    data = {}
    name = request.GET.get("name", None)

    if name is None:
        data['is_none'] = True 
    else:
        try:
            temp_category = Category.objects.get(name = name)
            data['is_exist'] = True

        except Category.DoesNotExist:
            temp_client = Client.objects.get(user = request.user)
            new_category = Category(name=name, client=temp_client)
            new_category.save()


            print("PK",new_category.pk)
            data['success'] = True
            data['obj'] = {
                'name': new_category.name.upper(),
                'id': new_category.pk
            }


    return JsonResponse(data)




    
#! Page 404
def page_404_view(request, exception):    
    template_name = "core/pages/404.html"

    path = request.path
    
    if path.startswith("/update/"):
        error = "update"
    else:
        error = None
    
    
    data = {
        'error': error
    }
    
    return render(request, template_name, data)

 

core/templates/core/modules/category/create_category.html
{% extends 'core/components/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Adicionar Categoria
{% endblock title %}




{% block content %}

<form action="" method="POST"> 
    {{form}}
    <button>Enviar</button>
</form>
{% endblock content %}

core/templates/core/modules/category/list_category.html
{% extends 'core/components/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Categorias
{% endblock title %}

{% block css %}

<link rel="stylesheet" href="{% static 'core/css/list-category-style.css' %}">

{% endblock css %}


{% block content %}

<div class="back_button">
    <a href="{% url 'core:list_transaction' %}" title="Voltar">
        <i class="fas fa-chevron-left" style="color: black;"></i>
    </a>
</div>

<div class="square d-flex align-items-center d-flex justify-content-center">
    <div>
        <div class="card shadow bg-white rounded">
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <h2 class="text-dark" style="font-family: 'Cairo', sans-serif;">Categorias</h2>
                    </div>

                    <div class="col-md-2">
                        <div class="d-flex justify-content-end">

                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-success" data-toggle="modal"
                                data-target="#exampleModal">
                                <i class="fas fa-plus"></i>
                            </button>
                        </div>

                    </div>
                </div>

            </div>
            <div class="card-body">


                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">TÍTULO</th>
                            <th class="text-center" scope="col">STATUS</th>
                            <th class="text-center" scope="col">EDITAR</th>
                            <th class="text-center" scope="col">REMOVER</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <td class="text-center"><b>{{ category.name|upper }}</b></td>
                            <td class="text-center">
                                {% if category.is_active %}
                                <span class="badge badge-success">ATIVO</span>
                                {% else %}
                                <span class="badge badge-danger">INATIVO</span>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a class="text-dark" href="#">
                                    <i class="fas fa-edit" id="edit"></i>
                                </a>
                            </td>

                            <td class="text-center">

                                <button type="button" id="delete" data-toggle="modal"
                                    style="background-color: transparent;" data-target="#modal-{{category.pk}}">
                                    <i class="fas fa-trash-alt"></i>
                                </button>


                                <div class="modal fade" id="modal-{{category.pk}}" tabindex="-1" role="dialog"
                                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                            <div class="modal-body">
                                                <h5>
                                                    Deseja realmente excluir a categoria <b>{{category.name|upper}}</b>?
                                                </h5>
                                            </div>
                                            <form action="{% url 'core:delete_category' category.pk %}" method="POST">
                                                <div class="modal-footer">
                                                    {% csrf_token %}

                                                    <button type="submit"
                                                        class="btn btn-danger btn-block">CONFIRMAR</button>


                                                    <button type="button" class="btn btn-outline-secondary btn-block"
                                                        data-dismiss="modal">VOLTAR</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>



                                <!-- <a class="text-dark" href="#">
                                    <i class="fas fa-trash-alt" id="delete"></i>
                                </a> -->
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>




            </div>
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination rounded">
                    <li class="page-item  {% if page_obj.has_previous == False %} disabled {% endif %}">
                        <a class="page-link" style=""
                            href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% else %} # {% endif %}">
                            <i class="fas fa-arrow-left"></i>
                        </a>
                    </li>

                    {% with ''|center:page_obj.paginator.num_pages as range %}
                    {% for _ in range %}
                    <li class="page-item {% if forloop.counter == page_obj.number %} active {% endif %}">
                        <a class="page-link" href="?page={{ forloop.counter}}" style="color: rgb(0, 0, 0);">
                            {{ forloop.counter}}
                        </a>
                    </li>
                    {% endfor %}
                    {% endwith %}

                    <li class="page-item  {% if page_obj.has_next == False %} disabled {% endif %}">
                        <a class="page-link"
                            href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% else %} # {% endif %}">
                            <i class="fas fa-arrow-right"></i>
                        </a>
                    </li>
                </ul>
            </nav>

        </div>
    </div>


</div>





<!-- Modal -->
<form action="{% url 'core:create_category' %}" method="POST">
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-dark" id="exampleModalLabel" style="font-family: 'Cairo', sans-serif;">Adicionar Categoria</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                    {% csrf_token %}
                    <label for="id_name"><b>Nome:</b></label>
                    <input class="form-control" type="text" name="name" maxlength="50" required="" id="id_name">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success btn-block">ADICIONAR</button>
                    <button type="button" class="btn btn-outline-secondary btn-block"
                        data-dismiss="modal">VOLTAR</button>
                </div>
            </div>
        </div>
    </div>
</form>


{% endblock content %}