ControleFinancas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path('accounts/', include("django.contrib.auth.urls")), #!Adicionar django.contrib.auth.urls para login/logout
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),

]


handler404 = 'core.views.page_404_view'

core/urls.py
from django.urls import path
from core.views import *

app_name = "core"
urlpatterns = [
    path("", TrasactionListView.as_view(), name="list_transaction"),
    path("create/", TransactionCreateView.as_view(), name="create_transaction"),
    path("update/<int:pk>/", TransactionUpdateView.as_view(), name="update_transaction"),
    path("delete/<int:pk>/", TransactionDeleteView.as_view(), name="delete_transaction"),
    path("create-category/", CategoryCreateView.as_view() , name="create_category"),
    path("list-category/", CategoryListView.as_view() , name="list_category"),
    path("delete-category/<int:pk>/", CategoryDeleteView.as_view() , name="delete_category"),
    path("ajax/new-category/", create_category_modal, name="new_category"),

]   

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Client(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField(verbose_name="Idade")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name.upper()


class Category(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=50, verbose_name="Nome")
    is_active = models.BooleanField(verbose_name="Ativo?", default = True, null=True, blank=True)

    def __str__(self):
        return self.name.upper()
    
class Transaction(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50, verbose_name="Título") 
    value = models.DecimalField(max_digits=7, decimal_places=2, verbose_name = "Valor")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Categoria", blank=True, null=True)
    date_now = models.DateTimeField(auto_now=True)
    date_trasaction = models.DateField(verbose_name="Data da Transação")
    description = models.TextField(verbose_name="Descrição", blank=True)
    

    def __str__(self):
        return self.title.upper()

    class Meta:
        ordering = ["-date_now"]






    

    
    

core/forms.py
from django.forms import ModelForm, Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from core.models import *





class TransactionForm(ModelForm):

    class Meta:
        model = Transaction
        fields = "__all__"
        exclude = ["client", ]

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
        exclude = ["client", "is_active", ]



   

core/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from core.models import *
from core.forms import *

from django.http import HttpResponseRedirect
from django.http.response import JsonResponse


#! Transaction
class TrasactionListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "core/modules/transaction/list_transaction.html"
    context_object_name = "transactions"
    paginate_by = 8

    
    def get_context_data(self, **kwargs):
        context = super(TrasactionListView, self).get_context_data(**kwargs)
        context['search_not_exist'] = True if (context['transactions'].count() == 0 and self.request.GET) else False
        context.update()
        return context
    
    def get_queryset(self, *args, **kwargs):
        qs = super(TrasactionListView, self).get_queryset(*args, **kwargs) 
        search = self.request.GET.get("id_search", None)
        
        

        if self.request.user.is_superuser is False:
            qs = qs.filter(client__user = self.request.user)
        
        if search is not None:
            qs = qs.filter(title__icontains = search)

        return qs 

  

class TransactionCreateView(LoginRequiredMixin, CreateView):
    model = Transaction
    form_class = TransactionForm
    template_name = "core/modules/transaction/create_transaction.html"
    success_url = reverse_lazy('core:list_transaction')

    def get_category_by_user(self, user):
        category = Category.objects.all()

        if (user.is_superuser is False):
            category = Category.objects.filter(client__user = user, is_active = True)
        
        return category

    def get_context_data(self, **kwargs):
        context = super(TransactionCreateView, self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = self.get_category_by_user(self.request.user)
        return context

    def form_valid(self, form):
        self.object = form.save()
        temp_client = Client.objects.get(user = self.request.user)
        self.object.client = temp_client
        self.object.save()

        return super().form_valid(form)

class TransactionUpdateView(LoginRequiredMixin, UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name = "core/modules/transaction/update_transaction.html"
    success_url = reverse_lazy('core:list_transaction')

    def get_category_by_user(self, user):
        category = Category.objects.all()

        if (user.is_superuser is False):
            category = Category.objects.filter(client__user = user, is_active = True)
        
        return category

    def get_context_data(self, **kwargs):
        context = super(TransactionUpdateView, self).get_context_data(**kwargs)
        context['form'].fields['category'].queryset = self.get_category_by_user(self.request.user)
        return context

class TransactionDeleteView(LoginRequiredMixin, DeleteView):
    model = Transaction
    success_url = reverse_lazy('core:list_transaction')

#! Category
class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = "core/modules/category/list_category.html"
    context_object_name = "categories"
    paginate_by = 3

    def get_queryset(self, *args, **kwargs):
        qs  = super(CategoryListView, self).get_queryset(*args, **kwargs)
        if self.request.user.is_superuser is False:
            qs = qs.filter(client__user = self.request.user)
        return qs

class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    
    def get_success_url(self):
        return self.request.META.get("HTTP_REFERER")




class CategoryCreateView(LoginRequiredMixin, View):
    model = Category
    form_class = CategoryForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            temp_client = Client.objects.get(user = self.request.user)
            self.object.client = temp_client
            self.object.save()
            
            data = {
                "status": 200,
                "id": self.object.pk,
                "name": self.object.name.upper(),
            }

        else:

            data = {
                "status": 500,
                "id": None,
                "name": None,
            }
        return data
        

        
        

    def post(self, request, *args, **kwargs):
        form = CategoryForm(request.POST)
        data = self.form_valid(form)
        return JsonResponse(data)


def create_category_modal(request):
    data = {}
    name = request.GET.get("name", None)

    if name is None:
        data['is_none'] = True 
    else:
        try:
            temp_category = Category.objects.get(name = name)
            data['is_exist'] = True

        except Category.DoesNotExist:
            temp_client = Client.objects.get(user = request.user)
            new_category = Category(name=name, client=temp_client)
            new_category.save()


            print("PK",new_category.pk)
            data['success'] = True
            data['obj'] = {
                'name': new_category.name.upper(),
                'id': new_category.pk
            }


    return JsonResponse(data)




    
#! Page 404
def page_404_view(request, exception):    
    template_name = "core/pages/404.html"

    path = request.path
    
    if path.startswith("/update/"):
        error = "update"
    else:
        error = None
    
    
    data = {
        'error': error
    }
    
    return render(request, template_name, data)

 

core/templates/core/modules/transaction/create_transaction.html
{% extends 'core/components/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Transação
{% endblock title %}


{% block css %}
<style>
    .add-category {
        background-color: transparent;
        color: blue;
        border: none;
        outline: none;
    }

    .add-category:focus {
        border: none;
        outline: none;
    }

    .add-category:hover {
        text-decoration: underline;
    }

    
</style>
{% endblock css %}



{% block content %}



<div class="alert alert-success alert-dismissible fade show" role="alert" id="div-alert">
    <p id="message_success"></p>
    
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>







<form action="" method="POST">
    {% csrf_token %}
    <div class="d-flex align-items-center d-flex justify-content-center" style="width: 100vw; height: 100vh;">


        <div class="card shadow  mb-3 bg-white rounded">
            <div class="card-header">
                <div class="d-flex justify-content-center">
                    <h3 class="text-dark" style="font-family: 'Cairo', sans-serif;">Adicionar Transação</h3>
                </div>
            </div>

            <div class="card-body">

                <div class="row">
                    <div class="col">
                        <b>{{form.title.label}}:</b>
                        {% render_field form.title class+="form-control" %}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <b>{{form.value.label}}:</b>
                        {% render_field form.value class+="form-control" %}
                    </div>

                    <div class="col">
                        <b>{{form.date_trasaction.label}}:</b>
                        {% render_field form.date_trasaction class+="form-control"  type='date' %}
                    </div>

                </div>

                <div class="row">
                    <div class="col">
                        <b>{{form.category.label}}:</b>
                        {% render_field form.category class+="form-control" %}
                        <small>
                            <button type="button" class="add-category" data-toggle="modal"
                                data-target="#adicionar_categoria">
                                Adicionar categoria
                            </button>
                        </small>

                    </div>


                </div>

                <div class="row">
                    <div class="col">
                        <b>{{form.description.label}}:</b>
                        {% render_field form.description class+="form-control" rows="3"  %}
                    </div>

                </div>


            </div>

            <div class="card-footer">
                <div class="row">
                    <div class="col">
                        <div class="d-flex justify-content-center">
                            <a class="btn btn-outline-secondary btn-block"
                                href="{% url 'core:list_transaction' %}">VOLTAR</a>
                        </div>
                    </div>
                    <div class="col">
                        <button class="btn btn-success btn-block" type="submit">ADICIONAR</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>


<form action="" id="formCreateCategory" method="POST">

    {% csrf_token %}

    <div class="modal fade" id="adicionar_categoria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header d-flex justify-content-center">
                    <h4 class="modal-title text-dark" id="exampleModalLabel" style="font-family: 'Cairo', sans-serif;">
                        Adicionar Categoria</h4>
                </div>
                <div class="modal-body">

                    <label for="id_name"><b>Nome:</b></label>
                    <input class="form-control" type="text" name="name" maxlength="50" required="" id="id_name"
                        placeholder="Ex.: Roupas, Sapatos, Medicamento ...">

                    <small class="" id="error_category" style="margin-top: 5px;display:none;color: #ED2939;">

                    </small>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success btn-block" type="button" id="buttonCreateCategory">ADICIONAR</button>

                    <button type="button" id="buttonCloseModal" class="btn btn-outline-secondary btn-block"
                        data-dismiss="modal">VOLTAR</button>
                </div>
            </div>
        </div>
    </div>

</form>

{% endblock content %}



{% block extra_js %}

<script src="{% static 'core/js/createCategory.js' %}"></script>


{% endblock extra_js %}

core/templates/core/modules/transaction/list_transaction.html
{% extends 'core/components/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}

{% block title %}
Lista de Transações
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'core/css/list-transaction-style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Assistant&family=Cairo:wght@700&display=swap" rel="stylesheet">

{% endblock css %}

{% block content %}

<br>
<div class="d-flex justify-content-center">

    <div class="card shadow-sm  bg-white rounded">
        <div class="card-body">

            <button type="button" class="btn btn-dark" disabled style="border-radius: 0px;">
                <span class="badge badge-light"><i class="fas fa-user"></i></span> {{request.user.username|upper}}
            </button>

            <a class="btn btn-info" style="color: white; border-radius: 0px;" href="{% url 'core:create_transaction' %}"
                title="Adicionar Transação">
                <i class="fas fa-plus"></i>
            </a>

            <a class="btn btn-dark" style="color: white; border-radius: 0px;" href="{% url 'core:list_category' %}"
                title="Lista de Categorias">
                <i class="fas fa-list"></i>
            </a>

            <a class="btn btn-danger" href="{% url 'logout' %}" title="Sair" style="border-radius: 0px;">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </div>

    </div>



</div>



<br>

<div class="container">
    <div class="card shadow-sm mb-5 bg-white rounded">
        <div class="card-header">

            <div class="row">
                <div class="col d-flex justify-content-start">
                    <h3>
                        <a class="text-dark" href="{% url 'core:list_transaction' %}"
                            style="font-family: 'Cairo', sans-serif;">Lista de Transações</a>
                    </h3>
                </div>
                <div class="col d-flex justify-content-end">
                    <form method="GET">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col" style="padding: 0px;">
                                <input class="form-control" type="text" placeholder="Buscar por título ..."
                                    name="id_search" type="search" style="border-radius: 0px;">
                            </div>
    
                            <div class="col" style="padding: 0px;">
                                <button class="btn btn-success"
                                    style="border-radius: 0px; border-bottom-right-radius: 0px;">
                                    <i class="fas fa-search-dollar"></i>
                                </button>
                            </div>
                        </div>

                    </form>
                </div>

            </div>





        </div>
        <div class="card-body" style="padding: 0px;">
            {% if transactions.count > 0 %}
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">Título</th>
                            <th class="text-center" scope="col">Valor(R$)</th>
                            <th class="text-center" scope="col">Categoria</th>
                            <th class="text-center" scope="col">Adicionado</th>
                            <th class="text-center" scope="col">Modificado</th>
                            <th class="text-center" scope="col">Remover</th>
                            <th class="text-center" scope="col">Editar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for transaction in transactions %}
                        <a href="{% url 'core:update_transaction' transaction.pk %}">


                            <tr class="teste">
                                <td class="text-center" id="title_label">
                                    <b>{{transaction.title}}</b>

                                </td>

                                <td class="text-center"> {{transaction.value}}</td>
                                <td class="text-center">
                                    {% if transaction.category is not None %}
                                        {{transaction.category}}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td class="text-center">{{transaction.date_trasaction}}</td>
                                <td class="text-center">{{transaction.date_now|naturaltime }}</td>
                                <td class="text-center">

                                    <button type="button" class="button-delete" data-toggle="modal"
                                        data-target="#modal-{{transaction.pk}}">
                                        <i class="fas fa-trash-alt" id="delete"></i>
                                    </button>


                                    <div class="modal fade" id="modal-{{transaction.pk}}" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">

                                                <div class="modal-body">
                                                    <h5 class="text-dark" style="font-family: 'Cairo', sans-serif;">
                                                        Deseja realmente excluir a transação
                                                        <b
                                                            style="color: rgb(101, 140, 223);">{{transaction.title|upper}}</b>?
                                                    </h5>
                                                </div>
                                                <form action="{% url 'core:delete_transaction' transaction.pk %}"
                                                    method="POST">
                                                    <div class="modal-footer">
                                                        {% csrf_token %}

                                                        <button type="submit"
                                                            class="btn btn-danger btn-block">CONFIRMAR</button>


                                                        <button type="button"
                                                            class="btn btn-outline-secondary btn-block"
                                                            data-dismiss="modal">VOLTAR</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center">

                                    <a class="text-dark" href="{% url 'core:update_transaction' transaction.pk %}">
                                        <i class="fas fa-edit" id="edit"></i>
                                    </a>
                                </td>
                            </tr>
                        </a>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            {% elif search_not_exist %}
            <div
                class="square-not-found d-flex align-items-center d-flex justify-content-center shadow-sm p-3 mb-5 bg-white rounded">
                <div class="">
                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-center">

                                <!-- <i class="far fa-frown-open" style="font-size: 10vw;"></i> -->
                                <i class="fas fa-search" style="font-size: 10vw;"></i>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-center">
                                <p class="h2" style="font-family: 'Cairo', sans-serif;">Não foi possível encontrar nada
                                    correspondente a sua
                                    pesquisa</p>


                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-center">
                                <a href="{% url 'core:list_transaction' %}" class="text-decoration-none"
                                    style="font-family: 'Assistant', sans-serif;">Listar todas as
                                    transações</a>

                            </div>
                        </div>
                    </div>

                </div>

            </div>
            {% else %}
            <div
                class="square-not-found d-flex align-items-center d-flex justify-content-center shadow-sm p-3 mb-5 bg-white rounded">
                <div class="">
                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-center">
                                <i class="far fa-frown-open" style="font-size: 10vw;"></i>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-center">
                                <p class="h2" style="font-family: 'Cairo', sans-serif;">Sua lista de transações está
                                    vazia!</p>


                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="d-flex justify-content-center">

                                <a href="{% url 'core:create_transaction' %}" class="text-decoration-none"
                                    style="font-family: 'Assistant', sans-serif;">Adicionar
                                    nova transação</a>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
            {% endif %}
        </div>
    </div>

</div>


<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination rounded">
            <li class="page-item  {% if page_obj.has_previous == False %} disabled {% endif %}">
                <a class="page-link" style=""
                    href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% else %} # {% endif %}">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </li>

            {% with ''|center:page_obj.paginator.num_pages as range %}
            {% for _ in range %}
            <li class="page-item {% if forloop.counter == page_obj.number %} active {% endif %}">
                <a class="page-link" href="?page={{ forloop.counter}}" style="color: rgb(0, 0, 0);">
                    {{ forloop.counter}}
                </a>
            </li>
            {% endfor %}
            {% endwith %}

            <li class="page-item  {% if page_obj.has_next == False %} disabled {% endif %}">
                <a class="page-link"
                    href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% else %} # {% endif %}">
                    <i class="fas fa-arrow-right"></i>
                </a>
            </li>
        </ul>
    </nav>

</div>






{% endblock content %}

core/templates/core/modules/transaction/update_transaction.html
{% extends 'core/components/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
Editar Transação
{% endblock title %}

{% block content %}



<div class="vw-100 vh-100 d-flex align-items-center d-flex justify-content-center">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="card shadow  mb-3 bg-white rounded">
            <div class="card-header">
                <div class="d-flex justify-content-center">
                    <h3 class="text-dark" style="font-family: 'Cairo', sans-serif;">Editar Transação</h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <b>{{form.title.label}}</b>
                        {% render_field form.title class+="form-control" %}

                        <small class="font-weight-bold" style="color: red;">
                            {% for error in form.title.errors %}
                            {{ error }}
                            {% endfor %}
                        </small>
                    </div>

                    <div class="col-md-5">
                        <b>{{form.date_trasaction.label}}</b>
                        {% render_field form.date_trasaction class+="form-control" type="date" %}

                        <small class="font-weight-bold" style="color: red;">
                            {% for error in form.date_trasaction.errors %}
                            {{ error }}
                            {% endfor %}
                        </small>
                    </div>

                </div>

                <div class="row">
                    <div class="col">
                        <b>{{form.category.label}}</b>
                        {% render_field form.category class+="form-control" %}
                        <small class="font-weight-bold" style="color: red;">
                            {% for error in form.category.errors %}
                            {{ error }}
                            {% endfor %}
                        </small>
                    </div>
                    <div class="col">
                        <b>{{form.value.label}}</b>
                        {% render_field form.value class+="form-control" %}
                        <small class="font-weight-bold" style="color: red;">
                            {% for error in form.value.errors %}
                            {{ error }}
                            {% endfor %}
                        </small>
                    </div>
                </div>



                <div class="row">
                    <div class="col">
                        <b>{{form.description.label}}:</b>
                        {% render_field form.description class+="form-control" rows="3" %}
                    </div>
                </div>








            </div>

            <div class="card-footer">
                <div class="row">
                    <div class="col">
                        <a href="{% url 'core:list_transaction' %}"
                            class="btn btn-outline-secondary  btn-block">VOLTAR</a>

                    </div>
                    <div class="col">

                        <button class="btn btn-success btn-block" type="submit">CONCLUIR</button>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>








{% endblock content %}